#!/bin/bash

filename=$1
riterator=1
rowadd=1
numrows=$(cat $filename | wc -l | tr -d $filename)
rowsize=$(cat $filename | head -n 1 | wc -w)
echo "#rows = $numrows"
echo "size = $rowsize"

while [ $riterator -le $numrows ]
do
	sum=0
	cat $filename | tail -n +$riterator | head -n 1 > temp
	while [ $rowadd -le $rowsize ]
	do
		sumadd=$(cat temp | cut -f $rowadd)
		sum=$((sum+sumadd))
		rowadd=$((rowadd+1))
	done	
	rowadd=1
	riterator=$((riterator+1))	
	echo "Sum: $sum"	
done
