#!/bin/bash

if [ "$#" -eq 1 ]
then
	echo "one input specified: $1"
elif [ "$#" -eq 2 ]
then
	echo "two inputs specified: $1, $2"
elif [ "$#" -ge 3 ]
then
	echo "more than two inputs specified. error."
elif [ "$#" -eq 0 ]
then
	echo "no inputs specified. error.":
fi
