#!/bin/bash

#clear #maybe make things pretty?


#program structure to determine which input was selected
getopts ":rc" opts #looks for options beginning with r or c
case $opts in
	r) #if -r option found, set rflag
		rflag=1
		cflag=0
		;;
	c) #if -c option found, set cflag
		rflag=0
		cflag=1
		;;
	\?) #otherwise exit
		echo "Usage: stats { -r | -c } [filename]"
		rflag=0
		cflag=0
		;;
esac

#statements to check arguments for errors
#determines program behavior
if [ $# -eq 0 ] #if no arguments
then
	exit 1 #or equivalent
	#stderr here?
elif [ $# -eq 1 ] #if one argument
then
	stdinflag=1;
	#maybe flag for stdin input instead of filename input?
	#	could mean two program flows, hmm...
elif [ $# -eq 2 ] #if two arguments
then
	stdinflag=0;
	filename=$2 #maybe set elsewhere?
elif [ $# -ge 3 ] #if more than two arguments
then
	echo "Usage: stats { -r | -c } [filename]"
	exit 1 #o equivalent
	#stderr here?
fi


if [ $stdinflag -eq 1 ]
then
	echo "Please input table:"
	#input stdin goes here
	#put into temp file, run rest of program
fi

#main program flow begins
if [ $rflag -eq 1 ]
then
	echo "===========" #make things pretty!
	echo "   Rows    "
	echo "==========="
	echo "Average Median"
	
	riterator=1
	numrows=$(cat $filename | wc -l | tr -d $filename)
	rowsize=$(cat $filename | head -n 1 | wc -w)

	while [ $riterator -le $numrows ]
	do
		mean=0
		sum=0
		sumadd=0
		rowadd=1
		cat $filename | tail -n +$riterator | head -n 1 > temp
		
		while [ $rowadd -le $rowsize ]
		do
			sumadd=$(cat temp | cut -f $rowadd)
			sum=$((sum+sumadd))
			rowadd=$((rowadd+1))
		done
		mean=$(((sum+(rowsize/2))/rowsize)) #calculates ROUNDED mean
	
		if (( $rowsize % 2 != 0 ))
		then
			midpoint=$(((rowsize/2)+1))
			median=$(cat $filename | tail -n +$riterator | head -n 1 | tr '\t' '\n' | sort -n | tr '\n' '\t' | cut -f $midpoint)
			echo "$mean     $median"
		else
			midpoint=$((rowsize/2))
			midtwo=$(((rowsize/2)+1))
			try1=$(cat $filename | tail -n +$riterator | head -n 1 | tr '\t' '\n' | sort -n | tr '\n' '\t' | cut -f $midpoint)
			try2=$(cat $filename | tail -n +$riterator | head -n 1 | tr '\t' '\n' | sort -n | tr '\n' '\t' | cut -f $midtwo)

			compresult=$(expr $try1 \< $try2)
			if [ $compresult -eq 1 ]
			then
				median=$try2
			else
				median=$try1
			fi
			
			echo "$mean       $median"
			
		fi	

		riterator=$((riterator+1))
	done
	if [ -e temp]
	then
		rm -f temp
	fi

elif [ $cflag -eq 1 ] #columns!
then

	echo "===========" #make things pretty!
	echo "   Cols    "
	echo "==========="
	echo "Average"

	citerator=1 #iterator variable
	numcols=$(cat $filename | head -n 1 | wc -w) #sets # columns
	colsize=$(cat $filename | cut -f 1 | wc -w) #sets size of columns



	while [ $citerator -le $numcols ] #for each column
	do

		#average time!
		mean=0 #average
		sum=0 #sum
		summand=0 #something to add to the sum
		addedcol=1 #column to add from in temp; not in $filename
		cat $filename | cut -f $citerator | tr '\n' '\t' > temp #cut column into temp; turn it into a row to ease manipulation in next step

		while [ $addedcol -le $colsize ] #iterate throgh the temp file's fields
		do
			summand=$(cat temp | cut -f $addedcol) #add each field to the sum
			sum=$((sum+summand))
			addedcol=$((addedcol+1)) #increase examined column
		done
		mean=$(((sum+(colsize/2))/colsize)) #calculates ROUNDED mean
		echo -n "$mean     "
		citerator=$((citerator+1))
	done

	citerator=1
	echo
	echo "Median"

	while [ $citerator -le $numcols ] #for each column
	do

		mean=0 #average
		sum=0 #sum
		summand=0 #something to add to the sum
		addedcol=1 #column to add from in temp; not in $filename
		#median time!
		if (( $colsize % 2 != 0 )) #if columns have odd # elements
		then
			midpoint=$(((colsize/2)+1)) #set logical midpoint


			#operation does these things in order:
			#1. Opens filename
			#2. Cuts out the citerator-th column
			#3. Sorts that column
			#4. Turns it into a row
			#5. Cuts out the number in position midpoint
			median=$(cat $filename | cut -f $citerator | sort -n | tr '\n' '\t' | cut -f $midpoint)


			echo "$mean       $median" #output mean and median
	
		else #otherwise # elements in column is even
			midpoint=$((colsize/2))
			midtwo=$((midpoint+1))
			#set two points to compare which is greater, output as median
			#proecss is identical to above, but second time looks at second "midpoint"
			try1=$(cat $filename | cut -f $citerator | sort -n | tr '\n' '\t' | cut -f $midpoint)
			try2=$(cat $filename | cut -f $citerator | sort -n | tr '\n' '\t' | cut -f $midtwo)
			
			#compares results of try1 and try2
			compresult=$(expr $try1 \< $try2)
			if [ $compresult -eq 1 ]
			then
				median=$try2 #if try1 < try2, output try2 
			else
				median=$try1 #if try1 > try2, output try1
			fi
			echo -n "$median     "
		
		fi

		citerator=$((citerator+1)) #iterate iterator
		
	done
echo
fi
